# Danish Documentation Configuration for MkDocs

site_name: PRO1 Kompendium
site_dir: ../site/da

# Documentation directory
docs_dir: docs

# Navigation for the documentation
nav:
  - Kapitel 1: chapter1.md
  - Kapitel 2: chapter2.md
  - Kapitel 3: chapter3.md
  - Kapitel 4: chapter4.md
  - Kapitel 5: chapter5.md
  - Kapitel 6: chapter6.md
  - Kapitel 7: chapter7.md
  - Kapitel 8: chapter8.md
  - Kapitel 9: chapter9.md
  - Kapitel 10: chapter10.md
  - Kapitel 11: chapter11.md
  - Kapitel 12: chapter12.md
  - Kapitel 13: chapter13.md
  - Kapitel 14: chapter14.md
  - Kapitel 15: chapter15.md
  - Kapitel 16: chapter16.md
  - Kapitel 17: chapter17.md
  - Kapitel 18: chapter18.md
  - Kapitel 19: chapter19.md
  - Bilag A: appendix_a.md
  - Bilag B: appendix_b.md
  - Bilag C: appendix_c.md
  - Bilag D: appendix_d.md
  - Bilag E: appendix_e.md